### ISSUE TITLE
problem in initialization 

### ISSUE THREAD

**Issue by Mohammad-Ahadinejad** [Cyfrin/2024-08-fjord#2]
I use "make init" command and have no error, but lib folder is still empty, therefore I cant build or test the project.

**Comment by k08t00mian** [comment]
same on my side

**Comment by christian1415** [comment]
same here

**Comment by BrysonHall** [comment]
same

**Comment by ThomasHeim11** [comment]
I have the same issue.

**Comment by ksmit323** [comment]
Oh thank god, I'm not the only one.

**Comment by EyanIngles** [comment]
run these command to get the lib files.
```bash
forge install transmissions11/solmate@v7 --no-commit
forge install OpenZeppelin/openzeppelin-contracts@v4.9.2 --no-commit
forge install sablier-labs/v2-core@v1.0.2 --no-commit
forge install PaulRBerg/prb-math --no-commit
forge install foundry-rs/forge-std --no-commit  
```

please also note that if you try to use forge update, it deletes some openzeppelin files that are needed, if you do use `forge update` just use the command `make init` and it will add them back in.

i am currently getting another issue which is: `Found incompatible Solidity versions:` to all the imported lib files.

**Comment by Mohammad-Ahadinejad** [comment]
1. First I clone the project from github  
`git clone https://github.com/Cyfrin/2024-08-fjord`
2. I installed all libraries manually as @EyanIngles  suggested.

> forge install transmissions11/solmate@v7 --no-commit
> forge install OpenZeppelin/openzeppelin-contracts@v4.9.2 --no-commit
> forge install sablier-labs/v2-core@v1.0.2 --no-commit
> forge install PaulRBerg/prb-math --no-commit
> forge install foundry-rs/forge-std --no-commit  

3. Then copied .env file with  `cp -iv .env.example .env`.
4.  at last I add my infura api key  in .env file.

everything worked fine for me . I can build or test the project with `forge build` and `forge test`
I didn't have "Found incompatible Solidity versions" error as @EyanIngles  mentioned.

**Comment by EyanIngles** [comment]
sorry i have fixed my own issue, what was happening is that i was using the command `make init`, which must of been installing the lib files differently but re-ran the command above, it works. very strange but fixed now.
